### ISSUE TITLE
Pcl Wrapper could not be found

### ISSUE THREAD

**Issue by ranjithksoman** [ph463/Gygax#32]
Hi, 
I am getting the following error when I try to build Gygax.sln.

Error	CS0246	The type or namespace name 'PclWrapper' could not be found (are you missing a using directive or an assembly reference?)	GygaxCore

**Comment by ph463** [comment]
Hi,
you need to build PclWrapper first (using cmake). Therefor you need to install PCL separately. If you have built is successfully you can find a pclwrapper.dll in your build directory.
