### ISSUE TITLE
protobuf-net

### ISSUE THREAD

**Issue by otofoto** [ph463/Gygax#33]
Unable to install protobuf-net on VS2012 - 'protobuf-net' already has a dependency defined for 'NETStandard.Library'.

**Comment by ph463** [comment]
Can you try [this](https://stackoverflow.com/questions/38654856/how-to-install-protobuf-net-on-visual-studio-2012-using-nuget)

**Comment by otofoto** [comment]
Seems to be installed but same issue:
```
PM> Install-Package protobuf-net -Version 2.0.0.668
'protobuf-net 2.0.0.668' already installed.
GygaxVisu already has a reference to 'protobuf-net 2.0.0.668'
```

Warning	2	This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\SharpDX.2.6.3\build\SharpDX.targets.	C:\Users\admins\Documents\VS-projects\Gygax-master\GygaxVisu\GygaxVisu.csproj	338	5	GygaxVisu

**Comment by otofoto** [comment]
![image](https://user-images.githubusercontent.com/26463333/52790248-c586ea80-306e-11e9-9aed-831735e32feb.png)
Ok, seems I need .NET 4.5.2 after all.

**Comment by otofoto** [comment]
Installing protobuf-portable-net solved the issue with .NET 4.5.2 version
